- hosts: all:!local
  gather_facts: yes

  tasks:
  - name: Ensure SELinux enabled
    lineinfile:
      dest: "/etc/sysconfig/selinux"
      regexp: '^{{ item.key }}='
      line: '{{ item.key }}={{ item.value }}'
      state: present
      create: yes
    with_items:
       - { key: 'SELINUX', value: 'enforcing' }
       - { key: 'SELINUXTYPE', value: 'targeted' }

  - name: Restart to enable
    command: /sbin/shutdown -r +1
    async: 0
    poll: 0
    ignore_errors: true
    when: reboot_host|default(false) == 'true'
