#
##
## !!! IMPORTANT !!!
## 
## NOTE: Ensure registration is done prior to running
## 
## Preparation steps:
## 
## Register machine with RH:
## ansible -i hosts OSEv3 -a 'subscription-manager register --username="username" --password="password"'
##
## Obtain the pool ID for Openshift:
## ansible -i hosts OSEv3 -a 'subscription-manager list --available --matches="*Openshift*"'
## 
## !!!!!!!!!!!!!!!!!
##
## prep-node-playbook.yaml: Quick playbook to prepare hosts for openshift-ansible deploy.
## 
## - Fills in docker-device to create docker-storage-setup file with proper values. (defaults: /dev/sdf)
## - Install and enable NetworkManager package
## - Ensure SELinux is enabled
## - Optionally reboot at end (required to enable SELinux)
##
## Takes OSEv3 inventory as input host file:
##     ansible-playbook -i hosts prep-node.yaml --limit 'node1.myenv.internal' -e 'pool=POOLID-FROM-COMMAND-ABOVE reboot_host=true'
##
## Optionally reboot server:
##     ansible-playbook -i hosts prep-node.yaml --limit 'node1.myenv.internal'  -e 'pool=POOLID-FROM-COMMAND-ABOVE reboot_host=true'
##
##
#

- hosts: all:!local
  gather_facts: yes
  vars:
     docker_device: vdb
     master_pool: "8a85XXX"
     infra_pool: "8a85XXX"
     node_pool: "8a85XXX"
     openshift_version: "3.6"

  tasks:
  - name: Ensure subscription-manager is installed
    yum: name="subscription-manager" state=latest

  - name: Verify if Master attached to proper pool already
    shell: subscription-manager list --consumed --pool-only|grep {{ master_pool }}
    when: openshift_node_labels['region'] == 'master'
    ignore_errors: true
    register: master_pool_attached

  - name: Verify if Infra node is attached to proper pool already
    shell: subscription-manager list --consumed --pool-only|grep {{ infra_pool }}
    when: openshift_node_labels['region'] == 'infra'
    ignore_errors: true
    register: infra_pool_attached

  - name: Verify if App node attached to proper pool already
    shell: subscription-manager list --consumed --pool-only|grep {{ node_pool }}
    when: openshift_node_labels['region'] == 'primary'
    ignore_errors: true
    register: node_pool_attached

  - name: Attach Master nodes to the appropriate pool-id
    shell: subscription-manager attach --pool={{ master_pool }}
    when: openshift_node_labels['region'] == 'master'


  - name: Attach Infra nodes to the appropriate pool-id
    shell: subscription-manager attach --pool={{ infra_pool }}
    when: openshift_node_labels['region'] == 'infra'

  - name: Attach App nodes to the appropriate pool-id
    shell: subscription-manager attach --pool={{ node_pool }}
    when: openshift_node_labels['region'] == 'primary'

  - name: Disable all repos
    shell: subscription-manager repos --disable="*"

  - name: Enable only required repos
    shell: subscription-manager repos --enable="rhel-7-server-rpms" --enable="rhel-7-server-extras-rpms" --enable="rhel-7-server-ose-{{ openshift_version }}-rpms" --enable="rhel-7-fast-datapath-rpms"

  - name: Install necessary packages
    yum: pkg={{ item }} state=installed
    with_items:
     - wget 
     - git 
     - net-tools 
     - bind-utils 
     - iptables-services 
     - bridge-utils 
     - bash-completion 
     - kexec-tools
     - sos
     - psacct

  - name: Ensure SELinux enabled
    lineinfile:
      dest: "/etc/sysconfig/selinux"
      regexp: '^{{ item.key }}='
      line: '{{ item.key }}={{ item.value }}'
      state: present
      create: yes
    with_items:
       - { key: 'SELINUX', value: 'enforcing' }
       - { key: 'SELINUXTYPE', value: 'targeted' }

  - name: Install correct docker version
    yum: name="docker-latest"

  - name: Set up docker-storage-setup file
    shell: echo -e 'DEVS=/dev/{{ docker_device }}\nVG=docker-vg\nDATA_SIZE=90%VG' > /etc/sysconfig/docker-storage-setup
    when: "'master' not in inventory_hostname"

  - name: Enable and start docker
    service: name=docker state=started enabled=yes

  - name: Install NetworkManager
    yum: name="NetworkManager" state=latest

  - name: Configure NetworkManager
    lineinfile:
      dest: "/etc/sysconfig/network-scripts/ifcfg-{{ ansible_default_ipv4['interface'] }}"
      regexp: '^{{ item }}='
      line: '{{ item }}=yes'
      state: present
      create: yes
    with_items:
    - 'USE_PEERDNS'
    - 'NM_CONTROLLED'

  - name: Enable NetworkManager
    service: name="NetworkManager" enabled=yes

  - name: Origin directory (for resolv.conf)
    file: name="/etc/origin" state=directory owner=root group=root mode=755

  - name: Create Origin's resolv.conf
    file: name="/etc/origin/resolv.conf" state=touch

  - name: Restart to enable
    command: /sbin/shutdown -r +1
    async: 0
    poll: 0
    ignore_errors: true
    when: reboot_host|default(false) == 'true'
